### ISSUE TITLE
特定Android端末で5分経過するだけでUV Scrollの見た目が大きく崩れる

### ISSUE THREAD

**Issue by masa-ibara** [Santarh/MToon#119]
こちらと同様の事象かと思われます。
https://forum.unity.com/threads/frac-_time-y-becomes-laggy-ony-android.825438/
独自のリセットされる時間変数を用意するなどで対応できないでしょうか。

- Snapdragon 855
- Snapdragon 860
- Snapdragon 765G
- Snapdragon 865 Plus 5G

の端末で発生を確認しました。

**Comment by Santarh** [comment]
報告ありがとうございます。

https://github.com/Santarh/MToon/pull/114 こちらの修正で直った可能性があります。
MToon [v3.9](https://github.com/Santarh/MToon/releases/tag/v3.9) 以降、または UniVRM [v0.107.0](https://github.com/vrm-c/UniVRM/releases/tag/v0.107.0) 以降ならば直っている可能性があります。

お使いのバージョン環境はいかがでしょうか？

**Comment by masa-ibara** [comment]
MToon v3.4でした。
アップデートしてみます🙏

**Comment by masa-ibara** [comment]
@Santarh 解決が確認できました。ありがとうございました。
