### ISSUE TITLE
機能に関する要望

### ISSUE THREAD

**Issue by Santarh** [Santarh/MToon#13]
適当にコメントしてください

**Comment by AlzioNever** [comment]
すみません、Github新入りなので、こういうのはissueにするべきかとかはわからないですが、
今Unityで最新版MToonを使っているですが、MToonを使っているモデルと光のインタラクションはちょっと変らしいです。例えばSpotlight（円錐形のライト）、光の範囲に入るとき、モデルの色の改変はスムースなのに、光の範囲から出るときはそうじゃないみたい。体の部位が光から出るとき、その部位の全体が一瞬でShade Colorになります。

主としてtransparentZWriteを使っているですが、この問題があったので、Opaque、Cutoutも試しました。でも問題は消えないです。こちらは僕の設定です。

https://puu.sh/BJLYi.png

よろしくお願いします。

**Comment by iCyP** [comment]
MToonの機能的バージョンがvectorProperties辺りに入ってると将来的にuniVRM外の人が助かると思います。

**Comment by iCyP** [comment]
_ReceiveShadowTextureがalpha参照になっていますが、red(ｸﾞﾚｽｹ)参照の方がalpha分テクスチャサイズ圧縮できるのではと思います。

**Comment by Santarh** [comment]
そうですね、Alpha になっているのはなぜなのでしょう？ってレベルなので、破壊的ではありますが変更したいと思います。

**Comment by simplestargame** [comment]
ミライ小町のシェーダー情報からやってきました。
こちらのナレッジで詳細確認しました。素敵なシェーダーですね。
https://niconare.nicovideo.jp/watch/kn3485

現在 LWRP + VRM ランタイムロードのゲームを作っていて、今は自前で変換後のシェーダーを用意してモデルを表示しています。
見た目を悪くする改悪行為なので、LWRP 対応がほしいと思ってました。

次の機能追加 Issue の MToon の LWRP 対応が入ること、心待ちにしています^^)
https://github.com/Santarh/MToon/issues/6

**Comment by Santarh** [comment]
ありがとうございます。
LWRP 対応は前向きに検討させていただきます！

**Comment by iCyP** [comment]
_UvAnimRotation は実装を見るに 値が1の時1回転/sec(0.01の時3.6°/sec回転)という認識なのですが、deg/sec等、分かりやすい単位にするか、ｲﾝｽﾍﾟｸﾀにどのような値なのか分かりやすい記述があったほうが良いのではないかと思いました。

**Comment by Santarh** [comment]
ご指摘の通り `1` で 1 回転 /sec となります。
値として `2pi` 以外の定数が存在せずシンプルな定義ゆえそうしましたが、ユーザインタフェースの観点からすると、おっしゃるとおりもう少し改善の余地ありかと思います。
考慮します。

**Comment by iCyP** [comment]
UI含め、_OutlineLightingMix関係の命名について、 Lighting -> SurfaceColor  等に置換すると実際の挙動に近くなると思いましたのでご提案します。名前から線色がライティングの影響を受けるだけと思っていたのですが、ニコナレの資料を参照すると、"本体の色とMixされる" とありましたので。
破壊的変更になるので、変更を入れられるような機会があれば、ご検討の程宜しくお願い致します。

**Comment by Santarh** [comment]
その点、たしかに誤解を与えている例が散見されるので、Inspector 上の UI としての名称変更は検討します。
内部の変数名としては変えるつもりはないです。
