### ISSUE TITLE
MToon1.8の光源反映で黄ばんで見えてしまう

### ISSUE THREAD

**Issue by fantom1x** [Santarh/MToon#34]
## 📝 概要 ##
　光源反映の機能 https://github.com/Santarh/MToon/pull/27 はシーンよってはとても有用ですが、Unity製でのVRMエクスポート(VRoidも含む)では、デフォルト光源色(Directional Light：#FFF4D6)が映り込むと白い服や肌が黄ばんで見えてしまうため、オプションとして切り替えられるようにして欲しいです（現存するVRMモデルのほとんどが影響を受けてしまってるため、できればデフォルトは従来どおりに、オプションで光源反映できる方が嬉しいです）。

●Unityのデフォルト光源色(Directional Light：#FFF4D6)
![unitydefaultlightcolor](https://user-images.githubusercontent.com/8603961/52172718-d014ca80-27b8-11e9-84df-50dae93da93d.jpg)

●MToon1.7 のときのサンプルA
![mtoon_1 7_sample_a](https://user-images.githubusercontent.com/8603961/52172650-6942e180-27b7-11e9-85cf-977a48179be7.jpg)
●MToon1.8 にしたときのサンプルA（一部MToonを使ってるテクスチャのみ黄ばんで見える[服,腕]）
![mtoon_1 8_sample_a](https://user-images.githubusercontent.com/8603961/52172653-6c3dd200-27b7-11e9-8b67-3a9ff23f7818.jpg)
●MToon1.7 のときのサンプルB
![mtoon_1 7_sample_b](https://user-images.githubusercontent.com/8603961/52172654-6fd15900-27b7-11e9-8fe0-4480952bae79.jpg)
●MToon1.8 にしたときのサンプルB（全体的にMToonを使っているため、服も肌も黄ばんで見える）
![mtoon_1 8_sample_b](https://user-images.githubusercontent.com/8603961/52172655-719b1c80-27b7-11e9-93bb-12179dde55f9.jpg)

## 💻 動作環境 ##
Unity 2018.3.3f1
UniVRM 0.48 (MToon1.7) / 0.49 (MToon1.8)
Windows10(x64) / Android 8.0

**Comment by Santarh** [comment]
光源の彩度を反映したくない場合は以下の解決法があります。
- `Light Color Attenuation` の値を上げる

またそもそも光源自体を反映したくない場合は以下の解決法があります。
- `Lit Color` と `Shade Color` を黒にし `Emission` にテクスチャと Color を割り当てる

**Comment by Santarh** [comment]
MToon は Unity の Standard シェーダと調和が取れるような結果を保つことを努力しています。
したがってデフォルトの動作はなるべく光源を反映させています。
どうしても「絶対この色を出したい！」という表現である場合は上記の解決法を試してみてください。

**Comment by Santarh** [comment]
また公式の VRM Viewer の光源色がこの色になっているのは見落としなので、こちらは #FFFFFF にしたいと思います。
