### ISSUE TITLE
Outline Noneの場合にアプリが固まる (Android一部端末)

### ISSUE THREAD

**Issue by d30835nm** [Santarh/MToon#36]
再現環境
端末名：ZenFone Go (ZB551KL)
OS：Android 5.1.1

UniVRM v0.43 → v0.49 へアップデートした際に、MtoonシェーダーのOutline Noneを設定しているマテリアルを利用していると、シーンごと落ちる不具合を確認しました。
上記記載の再現環境以外に4端末で確認しましたが、それらでは不具合は発生しておりません。
(Axon 7,Galaxy S6 Edge,Nexus 5X,Nexus 5)

下記の値を UnityObjectToClipPos(v.vertex) とすることで改善することが確認できています。
https://github.com/Santarh/MToon/blob/master/MToon/Resources/Shaders/MToonCore.cginc#L91

しかし、過去のコミットにて修正した記録があったため、こちらの対応が負荷削減などによるものであることも考慮し、対応についてはお任せいたたします。
85bdbdea1ee6d0496f892fddcb0f217330e128f1

**Comment by Santarh** [comment]
該当箇所のコードは描画されないことを目的としています。
そしてクラッシュの原因はゼロ除算だろうと推察されるので、出力値として適正な値に変更し、クリップ空間外の座標を明示的に指定するように変更いたしました。

ありがとうございます。
