### ISSUE TITLE
輪郭線幅のテクスチャに#010101より暗い点が入ると輪郭色に塗りつぶされる

### ISSUE THREAD

**Issue by m2wasabi** [Santarh/MToon#38]
アウトラインテクスチャで黒の塗りつぶし(#010101よりも暗い点)があると、マテリアル自体がアウトライン色に塗られてしまいます。

アウトラインのWidth Mode は `WorldCoordinates` , `ScreenCoordinates` のどちらでも発生します。

症状が出ているのはメッシュの中で裏からも見える部分のようです

エディタ内で確認。ビルド後もそうであるかは未確認です。

![image](https://user-images.githubusercontent.com/3489286/55337817-53f9e300-54da-11e9-8d89-ceb8b3a86204.png)

Platform: Windows10 Pro build 17134.648
Unity Editor version: 2018.2.15f1
UniVRM Version: 0.51.0

**Comment by Santarh** [comment]
ご報告ありがとうございます。

**Comment by Santarh** [comment]
Z-Fighting による問題だと推測します。

まず `WorldCoordinates` における線幅は `m` 単位です。
ここで添付していただいた画像の設定は `0.01m` に対して `1/256` を乗算して `0.04mm` 幅の輪郭線、ということになります。
これくらい細い輪郭線ですと、MToon に関係なく Z Buffer による深度テストに失敗して Z-Fighting に至ってしまうことがあります。

解決したいところではあるのですが、自分ではあまり良い解決策に至っておりません。
できれば細すぎる輪郭線はなるべく避けていただけると幸いです。

また他に解決策のほうがあればご教示いただければ幸いです。

**Comment by m2wasabi** [comment]
https://github.com/Santarh/MToon/blob/3b9347ae708ccc99e9d45903c73c935274ee7350/MToon/Resources/Shaders/MToonCore.cginc#L78-L79

ここですよね。
今の仕様だと微小値の積でオフセットに0に漸近する値を投入できてしまうので、
(極端な話テクスチャ値が0だと他のパラメータに何入れても無駄になる)
例えばオフセットに下限を設けるとかですかね。

**Comment by ghost** [comment]
訂正。
`WorldCoordinates` における線幅は `cm` 単位です。

したがって `0.01` かつ画像が `0x01` の場合 `0.0004mm` ですね…

**Comment by m2wasabi** [comment]
PullReqにて、ユーザー設定値の最終段をclampしてみました。こんな風ではいかがでしょう？

**Comment by Santarh** [comment]
この問題ですが、ZBuffer の精度に因るものです。
したがって、このシェーダがたとえば Unity 外に移植される場合には別の閾値になりえます。
そういった影響を考慮した結果、この問題は MToon の計算による頂点座標定義ではなく、
あくまで Unity に依存する解決法として Z Offset をかけることで解決したいと思います。
