### ISSUE TITLE
Assembly has reference to non-existent assembly 'MToon'

### ISSUE THREAD

**Issue by kknsy** [Santarh/MToon#48]
I opened this error after unlocking unity2018.3.14f1, how can I solve it?
![image](https://user-images.githubusercontent.com/26211860/57564456-7686f200-73de-11e9-9292-90f695ffc737.png)

**Comment by Santarh** [comment]
MToon v1.8 (included in latest UniVRM v0.51) has no assembly definition file.

You can download `MToon.asmdef` file from https://github.com/Santarh/MToon/tree/master/MToon and locate file in `Assets/VRM/MToon/MToon/MToon.asmdef` .

This issue will be resolved in next UniVRM version.
