### ISSUE TITLE
How about add Alpha to Coverage for MToon?

### ISSUE THREAD

**Issue by NoviaDroid** [Santarh/MToon#80]
It is a toon shader for vr character right? Maybe you should consider Alpha to Coverage :

[https://medium.com/@bgolus/anti-aliased-alpha-test-the-esoteric-alpha-to-coverage-8b177335ae4f]

I just simply add "AlphaToMask On" to mtoon shader, and it seems much better anti-aliasing under MSAA4x

**Comment by Santarh** [comment]
Thanks for your suggestion.
I didn't know that `AlphaToMask` property exists on Unity.
I'll investigate this. Thank you.
