### ISSUE TITLE
Shade Colorが設定した色より明るくなっている

### ISSUE THREAD

**Issue by MIAUMR** [Santarh/MToon#85]
MToonを最新版にしたところUnity上で影色が明るく表示されるようになってしまいました。
LitやRimは問題ないので修正をお願いします。

**Comment by Santarh** [comment]
ご報告ありがとうございます。
返答としましては、光源環境のほうを修正していただくのがベストかなと思われます。

理由といたしましては以下のとおりです。
MToon は「光源環境の影響を受けて陰影をつける」処理をしている以上、いつでもカラーコード通りの色が出るわけではありません。たとえば Unity で Scene を作ったときに設定されている光源環境は、太陽光の Directional Light と Skybox の Ambient Light を足して合わせて１００％よりも強い光が設定されています。したがってその場合、Shade Color も若干明るくなってしまいます。

光源の設定例としては以下のとおりです。
- すべて Lit な状態にしたい
  - DirectionalLight 無し、Ambient Light 白
- Lit Color & Shader Color をなるべく忠実に出したい
  - DirectionalLight 白、Ambient Light 無し
- 指定した色をなるべく出す感じでなんとなくうまい感じにしたい
  - DirectionalLight と Ambient Light の強さが足して 100% になるようにする

**Comment by MIAUMR** [comment]
ご返答ありがとうございます。
以前のバージョンからライティングの仕様が変更されていたんですね。
Environment Lightingを0にしたら解決できました。
環境光の設定については既存のチュートリアルに載っていないので、新たに詳細を追記されたほうが初心者にも分かりやすいかと思います。
