### ISSUE TITLE
質問 UniVRM0.53と0.51でのGI Intensityの処理の違いについて

### ISSUE THREAD

**Issue by m-sigepon** [Santarh/MToon#88]
UniVRM0.51に含まれるMToonと、UniVRM0.53に含まれるMToonでGI Intensityの値を1にした際に白飛びしていた状態が白飛びしなくなったのは下記の修正によるものでしょうか？
https://github.com/Santarh/MToon/pull/77

UniVRM 0.51に含まれるMToon
![image](https://user-images.githubusercontent.com/26161297/61681774-d5a3a400-ad49-11e9-82d1-20a6d4126ff7.png)

UniVRM 0.53に含まれるMToon
![image](https://user-images.githubusercontent.com/26161297/61681795-f3710900-ad49-11e9-8406-95386bc31164.png)

**Comment by Santarh** [comment]
はい。 Ambient Light と主要な Directional Light によって白飛びしなくなったのは #77 の変更によるものです。
この点は迷ったのですが、主な VR ・モバイル向けのユースケースにおいては白飛びしないほうが吉であると判断したためです。

逆に HDR をフルに活用していて、強い光源環境下における Auto Exposure などを使用している場合は暗くなりすぎてしまいますが、その場合は該当箇所をコメントアウトして運用していただくという想定です。
https://github.com/Santarh/MToon/blob/master/MToon/Resources/Shaders/MToonCore.cginc#L214

**Comment by m-sigepon** [comment]
ご返答ありがとうございます。
利用ケースに合わせてシェーダーを変更するので了解しました。
