### ISSUE TITLE
陰面消去された面が輪郭描画により輪郭色で埋められる

### ISSUE THREAD

**Issue by iCyP** [Santarh/MToon#89]
下画像例において、陰面消去によりワンピースの袖内側全面が透過されることを私は期待します。
しかし、実際はアウトライン描画処理により黒い面で埋められます。また、陰面消去された面の輪郭線も描画されているのではないかと疑えます。
これは意図されたものでしょうか？
<img width="821" alt="無題" src="https://user-images.githubusercontent.com/3232308/61783706-41b60300-ae43-11e9-8d42-4f80fde5a878.png">

**Comment by Santarh** [comment]
はい、この状態で問題ないと私は考えます。

輪郭線は、本来のポリゴンを拡大反転させたものが存在しているにすぎないため、存在するポリゴンを描画した結果としてこの状態は正しいと考えます。

もちろん、このような状態が見た目として不十分であるという考えは理解できます。
この状態を回避して見た目を良くするには以下の手段が考えられます。

- Z Write だけを行う描画パスを追加する
- Stencil を用いる

しかしながら、前者はシェーダの負荷、後者は可搬性の面で採用することはできません。

なにか他に良い実現手段があればぜひご提案ください。以上です。

**Comment by Santarh** [comment]
追記

この画像のケースにおける、私の考えるベストな解決法を提示します。
それは袖の内側にポリゴンを作成する、です。
見た目を気にする箇所は、モデル作成のレベルで形を整えることが重要だと考えます。

**Comment by iCyP** [comment]
シェーダの立ち位置からの制約による仕様という認識で承知しました。ご回答ありがとうございます。

あまり無いケースとは思いますが、例えば背景においてマジックミラーのような、表面からは見えないが逆側から透けて見えるというトリックを輪郭線有りオブジェクトでは作成できないことがあるかなと思った次第です。
