### ISSUE TITLE
バーチャルキャスト上でリムライトの座標計算がおかしい

### ISSUE THREAD

**Issue by Santarh** [Santarh/MToon#9]

**Comment by Santarh** [comment]
どうもローカルで再現しないなと思ったら、ランタイムロード時の問題らしい？

**Comment by Santarh** [comment]
あと法線マップ周り？

**Comment by m-sigepon** [comment]
ランタイムロードをUnity上で行った場合、手動でノーマルマップをFixすると正しい状態になるようです（v0.4.3で確認）
これを、UniVRMでマップに対して自動で行えば正しい結果になると思います。

**Comment by Santarh** [comment]
ありがとうございます！
これは MToon の問題というより UniVRM での法線マップ変換の問題だという見通しがあるので
そちらで解決したいと思います。

**Comment by Santarh** [comment]
UniVRM の法線マップ問題なので MToon としては Close
