### ISSUE TITLE
カスタム法線が反映されていない

### ISSUE THREAD

**Issue by iCyP** [Santarh/MToon#92]
下記SSの通り、MToonのシェーディングにカスタム法線が使用されていないように見えるのですが、仕様でしょうか？
<img width="1602" alt="無題" src="https://user-images.githubusercontent.com/3232308/63972200-2a71d180-cae3-11e9-8310-a5531edea7e0.png">
https://hub.vroid.com/characters/9169676169127779058/models/5249837227516583140
モデルはこちらからDLできます

**Comment by Santarh** [comment]
光源方向と Shade Color の設定具合で陰影が出にくい設定になっているようです。

![image](https://user-images.githubusercontent.com/328204/63973775-6eb2a100-cae6-11e9-94e6-e4a5caa94337.png)

**Comment by iCyP** [comment]
設定違いでした。申し訳ございません。
