### ISSUE TITLE
Unity2019 Android GLES2.0 problem

### ISSUE THREAD

**Issue by mhama** [Santarh/MToon#94]
Hi, I built android apk with UniVRM & the latest MToon with Unity2019.3.2f1 & GLES2.0, VRM models created with VRoid Studio look like this. (on Oculus Go)

<img width="300px" src="https://user-images.githubusercontent.com/618417/75537538-a3ce8a80-5a5a-11ea-97b6-ab59ca978b5f.jpg" />

It must look like below. (The same model and settings, captured with Unity Editor)
<img width="300px" src="https://user-images.githubusercontent.com/618417/75537861-13447a00-5a5b-11ea-993d-c50f207e6daa.png">

Is there any way to fix this problem? I need to use GLES2.0 rather than GLES3.0, due to a bit strange reason.

**Comment by mhama** [comment]
I found that the main reason is that GLES2 on Android (SnapDragon 821, 835) does't support `BlendOp Min` nor `BlendOp Max` . 

So I modified
```
BlendOp Add, Max
```
to
```
BlendOp Add, Add
```
in MToon.shader and the problem looks to be solved.
Is there any reason to require `Max` blendop?

(日本語でもOKです)

**Comment by Santarh** [comment]
Thanks for your report.
Yes, `BlendOp Add, Add` is Unity's default behaviour. and its solution is desirable.

MToon uses `BlendOp Add, Max` to render alpha channel correctly.
You can use `BlendOp Add, Add` if you don't need alpha channel.

And I will check `BlendOp` behaviour in OpenGL ES 2.0. Thank you.

**Comment by Santarh** [comment]
Related Issue
https://github.com/Santarh/MToon/issues/10
https://github.com/vrm-c/UniVRM/issues/28
