### ISSUE TITLE
Incompatible with Unity's Universal Render Pipeline (URP)?

### ISSUE THREAD

**Issue by SJT1988** [Santarh/MToon#95]
I imported a fresh `.VRM` model to a new Unity `URP` project. I have installed the `UniVRM` package. All of the model's materials are pink. There is nothing wrong with the textures. This seems to be a compatibility issue. Will this shader be updated soon?

**Comment by Santarh** [comment]
Thanks for your question.
MToon for URP is in milestone, but not implemented yet.
This issue is high priority, I think.

**Comment by breadnone** [comment]
ANy news on this?
